version: "3"
services:
  master:
    platform: linux/amd64
    build:
      context: ./couchbase
      dockerfile: Dockerfile
    ports:
      - 8091
      - 8092
      - 8093
      - 8094
      - 11210

  worker:
    platform: linux/amd64
    build:
      context: ./couchbase
      dockerfile: Dockerfile
    environment:
      MASTER: master:8091
    ports:
      - 8091
      - 8092
      - 8093
      - 8094
      - 11210

#  zookeeper:
#    container_name: zookeeper
#    image: zookeeper
#    networks:
#      couchbase-net:
#        ipv4_address: 172.16.101.5
#    depends_on:
#      - db3

#  kafka:
#    container_name: kafka
#    build:
#      context: ./kafka
#      dockerfile: Dockerfile
#    networks:
#      couchbase-net:
#        ipv4_address: 172.16.101.6
#    depends_on:
#      - zookeeper

#  vertx:
#    container_name: vertx
#    build:
#      context: ./counter
#      dockerfile: Dockerfile
#    networks:
#      couchbase-net:
#        ipv4_address: 172.16.101.7
#    ports:
#      - 7896:7896
#    depends_on:
#      - kafka
#      - db3

networks:
  couchbase-net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.101.0/16"