apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==  # Administrator
  password: cGFzc3dvcmQ=          # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
spec:
  memoryQuota: 128Mi
  replicas: 1
  ioPriority: high
  evictionPolicy: fullEviction
  conflictResolution: seqno
  enableFlush: true
  enableIndexReplica: false
  compressionMode: "off"
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:6.6.2
  security:
    adminSecret: cb-example-auth
  networking:
    exposeAdminConsole: true
    adminConsoleServiceTemplate:
      spec:
        type: NodePort
    exposedFeatures:
      - admin
      - client
    exposedFeatureServiceTemplate:
      spec:
        type: NodePort
    adminConsoleServices:
      - data
  buckets:
    managed: true
  servers:
    - size: 2
      name: all_services
      services:
        - data
        - index
        - query
      #  - search
      #  - eventing
      #  - analytics